//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace RazorCommonLibrary.Resource {
    using System;
    
    
    /// <summary>
    ///   用於查詢當地語系化字串等的強類型資源類別。
    /// </summary>
    // 這個類別是自動產生的，是利用 StronglyTypedResourceBuilder
    // 類別透過 ResGen 或 Visual Studio 這類工具。
    // 若要加入或移除成員，請編輯您的 .ResX 檔，然後重新執行 ResGen
    // (利用 /str 選項)，或重建您的 VS 專案。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class RCLLanguage {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RCLLanguage() {
        }
        
        /// <summary>
        ///   傳回這個類別使用的快取的 ResourceManager 執行個體。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RazorCommonLibrary.Resource.RCLLanguage", typeof(RCLLanguage).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   覆寫目前執行緒的 CurrentUICulture 屬性，對象是所有
        ///   使用這個強類型資源類別的資源查閱。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查詢類似 Condition String 的當地語系化字串。
        /// </summary>
        public static string Condition_String {
            get {
                return ResourceManager.GetString("Condition String", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Connection Type 的當地語系化字串。
        /// </summary>
        public static string Connection_Type {
            get {
                return ResourceManager.GetString("Connection Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Custom Status Category 的當地語系化字串。
        /// </summary>
        public static string Custom_Status_Category {
            get {
                return ResourceManager.GetString("Custom Status Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Data Type 的當地語系化字串。
        /// </summary>
        public static string Data_Type {
            get {
                return ResourceManager.GetString("Data Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Disconnect 的當地語系化字串。
        /// </summary>
        public static string Disconnect {
            get {
                return ResourceManager.GetString("Disconnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Enable 的當地語系化字串。
        /// </summary>
        public static string Enable {
            get {
                return ResourceManager.GetString("Enable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Error 的當地語系化字串。
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Error Code Category 的當地語系化字串。
        /// </summary>
        public static string Error_Code_Category {
            get {
                return ResourceManager.GetString("Error Code Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Hi 的當地語系化字串。
        /// </summary>
        public static string Hi {
            get {
                return ResourceManager.GetString("Hi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Idle 的當地語系化字串。
        /// </summary>
        public static string Idle {
            get {
                return ResourceManager.GetString("Idle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Init 的當地語系化字串。
        /// </summary>
        public static string Init {
            get {
                return ResourceManager.GetString("Init", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Input/Output 的當地語系化字串。
        /// </summary>
        public static string Input_Output {
            get {
                return ResourceManager.GetString("Input/Output", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 IP 的當地語系化字串。
        /// </summary>
        public static string IP {
            get {
                return ResourceManager.GetString("IP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Login 的當地語系化字串。
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Logout 的當地語系化字串。
        /// </summary>
        public static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 MaxRetryCount 的當地語系化字串。
        /// </summary>
        public static string MaxRetryCount {
            get {
                return ResourceManager.GetString("MaxRetryCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 ms 的當地語系化字串。
        /// </summary>
        public static string ms {
            get {
                return ResourceManager.GetString("ms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Name 的當地語系化字串。
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Not Defined 的當地語系化字串。
        /// </summary>
        public static string Not_Defined {
            get {
                return ResourceManager.GetString("Not Defined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Offset 的當地語系化字串。
        /// </summary>
        public static string Offset {
            get {
                return ResourceManager.GetString("Offset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Password 的當地語系化字串。
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Pause 的當地語系化字串。
        /// </summary>
        public static string Pause {
            get {
                return ResourceManager.GetString("Pause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Port 的當地語系化字串。
        /// </summary>
        public static string Port {
            get {
                return ResourceManager.GetString("Port", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Role 的當地語系化字串。
        /// </summary>
        public static string Role {
            get {
                return ResourceManager.GetString("Role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Running 的當地語系化字串。
        /// </summary>
        public static string Running {
            get {
                return ResourceManager.GetString("Running", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Special Type 的當地語系化字串。
        /// </summary>
        public static string Special_Type {
            get {
                return ResourceManager.GetString("Special Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Start Index 的當地語系化字串。
        /// </summary>
        public static string Start_Index {
            get {
                return ResourceManager.GetString("Start Index", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Station No 的當地語系化字串。
        /// </summary>
        public static string Station_No {
            get {
                return ResourceManager.GetString("Station No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Status 的當地語系化字串。
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Stop 的當地語系化字串。
        /// </summary>
        public static string Stop {
            get {
                return ResourceManager.GetString("Stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Tag 的當地語系化字串。
        /// </summary>
        public static string Tag {
            get {
                return ResourceManager.GetString("Tag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 TagCategory 的當地語系化字串。
        /// </summary>
        public static string Tag_Category {
            get {
                return ResourceManager.GetString("Tag Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Tag Count 的當地語系化字串。
        /// </summary>
        public static string Tag_Count {
            get {
                return ResourceManager.GetString("Tag Count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 TryConnecting 的當地語系化字串。
        /// </summary>
        public static string TryConnecting {
            get {
                return ResourceManager.GetString("TryConnecting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Update By Time 的當地語系化字串。
        /// </summary>
        public static string Update_By_Time {
            get {
                return ResourceManager.GetString("Update By Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 UpdateDelay 的當地語系化字串。
        /// </summary>
        public static string UpdateDelay {
            get {
                return ResourceManager.GetString("UpdateDelay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 User 的當地語系化字串。
        /// </summary>
        public static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
    }
}
