//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TMWeb.Resource {
    using System;
    
    
    /// <summary>
    ///   用於查詢當地語系化字串等的強類型資源類別。
    /// </summary>
    // 這個類別是自動產生的，是利用 StronglyTypedResourceBuilder
    // 類別透過 ResGen 或 Visual Studio 這類工具。
    // 若要加入或移除成員，請編輯您的 .ResX 檔，然後重新執行 ResGen
    // (利用 /str 選項)，或重建您的 VS 專案。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Language {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Language() {
        }
        
        /// <summary>
        ///   傳回這個類別使用的快取的 ResourceManager 執行個體。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TMWeb.Resource.Language", typeof(Language).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   覆寫目前執行緒的 CurrentUICulture 屬性，對象是所有
        ///   使用這個強類型資源類別的資源查閱。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查詢類似 Command 的當地語系化字串。
        /// </summary>
        public static string Command {
            get {
                return ResourceManager.GetString("Command", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Connection 的當地語系化字串。
        /// </summary>
        public static string Connection {
            get {
                return ResourceManager.GetString("Connection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Delpoy 的當地語系化字串。
        /// </summary>
        public static string Deploy {
            get {
                return ResourceManager.GetString("Deploy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Detail 的當地語系化字串。
        /// </summary>
        public static string Detail {
            get {
                return ResourceManager.GetString("Detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Developer 的當地語系化字串。
        /// </summary>
        public static string Developer {
            get {
                return ResourceManager.GetString("Developer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Disconnect 的當地語系化字串。
        /// </summary>
        public static string Disconnect {
            get {
                return ResourceManager.GetString("Disconnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Enable 的當地語系化字串。
        /// </summary>
        public static string Enable {
            get {
                return ResourceManager.GetString("Enable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Error 的當地語系化字串。
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Idle 的當地語系化字串。
        /// </summary>
        public static string Idle {
            get {
                return ResourceManager.GetString("Idle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Image 的當地語系化字串。
        /// </summary>
        public static string Image {
            get {
                return ResourceManager.GetString("Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Index 的當地語系化字串。
        /// </summary>
        public static string Index {
            get {
                return ResourceManager.GetString("Index", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Init 的當地語系化字串。
        /// </summary>
        public static string Init {
            get {
                return ResourceManager.GetString("Init", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Item 的當地語系化字串。
        /// </summary>
        public static string Item {
            get {
                return ResourceManager.GetString("Item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Item Record 的當地語系化字串。
        /// </summary>
        public static string Item_Record {
            get {
                return ResourceManager.GetString("Item Record", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 List 的當地語系化字串。
        /// </summary>
        public static string List {
            get {
                return ResourceManager.GetString("List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Lot 的當地語系化字串。
        /// </summary>
        public static string Lot {
            get {
                return ResourceManager.GetString("Lot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Machine 的當地語系化字串。
        /// </summary>
        public static string Machine {
            get {
                return ResourceManager.GetString("Machine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Machine Dashboard 的當地語系化字串。
        /// </summary>
        public static string Machine_Dashboard {
            get {
                return ResourceManager.GetString("Machine Dashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Map 的當地語系化字串。
        /// </summary>
        public static string Map {
            get {
                return ResourceManager.GetString("Map", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Name 的當地語系化字串。
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 NG 的當地語系化字串。
        /// </summary>
        public static string NG {
            get {
                return ResourceManager.GetString("NG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 OK 的當地語系化字串。
        /// </summary>
        public static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Part No 的當地語系化字串。
        /// </summary>
        public static string Part_No {
            get {
                return ResourceManager.GetString("Part No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Pause 的當地語系化字串。
        /// </summary>
        public static string Pause {
            get {
                return ResourceManager.GetString("Pause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Process 的當地語系化字串。
        /// </summary>
        public static string Process {
            get {
                return ResourceManager.GetString("Process", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Query 的當地語系化字串。
        /// </summary>
        public static string Query {
            get {
                return ResourceManager.GetString("Query", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Recipe 的當地語系化字串。
        /// </summary>
        public static string Recipe {
            get {
                return ResourceManager.GetString("Recipe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Record 的當地語系化字串。
        /// </summary>
        public static string Record {
            get {
                return ResourceManager.GetString("Record", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Running 的當地語系化字串。
        /// </summary>
        public static string Running {
            get {
                return ResourceManager.GetString("Running", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Script 的當地語系化字串。
        /// </summary>
        public static string Script {
            get {
                return ResourceManager.GetString("Script", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Sequence 的當地語系化字串。
        /// </summary>
        public static string Sequence {
            get {
                return ResourceManager.GetString("Sequence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Serial No 的當地語系化字串。
        /// </summary>
        public static string Serial_No {
            get {
                return ResourceManager.GetString("Serial No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Service 的當地語系化字串。
        /// </summary>
        public static string Service {
            get {
                return ResourceManager.GetString("Service", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Setting 的當地語系化字串。
        /// </summary>
        public static string Setting {
            get {
                return ResourceManager.GetString("Setting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Shopfloor 的當地語系化字串。
        /// </summary>
        public static string Shopfloor {
            get {
                return ResourceManager.GetString("Shopfloor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Start time 的當地語系化字串。
        /// </summary>
        public static string Start_Time {
            get {
                return ResourceManager.GetString("Start Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Station 的當地語系化字串。
        /// </summary>
        public static string Station {
            get {
                return ResourceManager.GetString("Station", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Station Dashboard 的當地語系化字串。
        /// </summary>
        public static string Station_Dashboard {
            get {
                return ResourceManager.GetString("Station Dashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Station in 的當地語系化字串。
        /// </summary>
        public static string Station_in {
            get {
                return ResourceManager.GetString("Station in", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Station out 的當地語系化字串。
        /// </summary>
        public static string Station_out {
            get {
                return ResourceManager.GetString("Station out", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Status 的當地語系化字串。
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Stop 的當地語系化字串。
        /// </summary>
        public static string Stop {
            get {
                return ResourceManager.GetString("Stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Tag 的當地語系化字串。
        /// </summary>
        public static string Tag {
            get {
                return ResourceManager.GetString("Tag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Target 的當地語系化字串。
        /// </summary>
        public static string Target {
            get {
                return ResourceManager.GetString("Target", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Task Record 的當地語系化字串。
        /// </summary>
        public static string Task_Record {
            get {
                return ResourceManager.GetString("Task Record", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Type 的當地語系化字串。
        /// </summary>
        public static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Uninit 的當地語系化字串。
        /// </summary>
        public static string Uninit {
            get {
                return ResourceManager.GetString("Uninit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Workorder 的當地語系化字串。
        /// </summary>
        public static string Workorder {
            get {
                return ResourceManager.GetString("Workorder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Workorder Recipe 的當地語系化字串。
        /// </summary>
        public static string Workorder_Recipe {
            get {
                return ResourceManager.GetString("Workorder Recipe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Workorder Record 的當地語系化字串。
        /// </summary>
        public static string Workorder_Record {
            get {
                return ResourceManager.GetString("Workorder Record", resourceCulture);
            }
        }
    }
}
